apiVersion: v1
kind: Service
metadata:
  name: states
  namespace: default
  labels:
    app: states
spec:
  type: LoadBalancer
  selector:
    app: states
  ports:
    - name: http
      port: 30081
      targetPort: 8000