apiVersion: v1
kind: Service
metadata:
  name: rooms
  namespace: default
  labels:
    app: rooms
spec:
  type: LoadBalancer
  selector:
    app: rooms
  ports:
    - name: http
      port: 30085
      targetPort: 8000