apiVersion: v1
kind: Secret
metadata:
  name: rooms-db-credentials
  namespace: default
  labels:
    app: rooms
type: Opaque
stringData:
  ROOMS_DB_URL: "mysql+asyncmy://root:password:rooms-db.default.svc.cluster.local:3306/rooms"
  rooms-root-password: password