apiVersion: v1
kind: Secret
metadata:
  name: bookings-db-credentials
  namespace: default
type: Opaque
stringData:
  DB_HOST: "bookings-db"
  DB_PORT: "30085"
  DB_USER: "root"
  bookings-root-password: "password"
  DB_NAME: "bookings"
  BOOKINGS_DB_URL: mysql+asyncmy://root:password@bookings-db.default.svc.cluster.local:3306/bookings 