apiVersion: v1
kind: Service
metadata:
  name: bookings
  namespace: default
  labels:
    app: bookings
spec:
  type: LoadBalancer
  selector:
    app: bookings
  ports:
    - name: http
      port: 30085
      targetPort: 8000