apiVersion: v1
kind: Secret
metadata:
  name: admins-db-credentials
  namespace: default
type: Opaque
stringData:
  ADMINS_DB_URL: mysql+asyncmy://root:password@admins-db.default.svc.cluster.local:3306/admins
  admins-root-password: password