apiVersion: v1
kind: Service
metadata:
  name: transactions
  namespace: default
  labels:
    app: transactions
spec:
  type: LoadBalancer
  selector:
    app: transactions
  ports:
    - name: http
      port: 30087
      targetPort: 8000