apiVersion: v1
kind: Secret
metadata:
  name: transactions-db-credentials
  namespace: default
type: Opaque
stringData:
  transactions-root-password: password
  TRANSACTIONS_DB_URL: mysql+asyncmy://root:password@transactions-db.default.svc.cluster.local:3306/transactions