apiVersion: v1
kind: Service
metadata:
  name: hotels
  namespace: default
  labels:
    app: hotels
spec:
  type: LoadBalancer
  selector:
    app: hotels
  ports:
    - name: http
      port: 30084
      targetPort: 8000