apiVersion: v1
kind: Secret
metadata:
  name: hotels-db-credentials
  namespace: default
type: Opaque
stringData:
  HOTELS_DB_URL: mysql+asyncmy://root:password@hotels-db.default.svc.cluster.local:3306/hotels
  hotels-root-password: password