apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  namespace: default
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer-service
          image: mwyoung414/customer-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000           
          env:
            - name: CUSTOMER_DB_URL
              valueFrom:
                secretKeyRef:
                  name: customer-db-credentials
                  key: CUSTOMER_DB_URL
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: customer-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: customer-config
                  key: DB_PORT
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
