apiVersion: v1
kind: Service
metadata:
  name: customer
  namespace: default
  labels:
    app: customer
spec:
  type: LoadBalancer
  selector:
    app: customer
  ports:
    - name: http
      port: 30082
      targetPort: 8000