apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: registration
  namespace: default
  labels:
    app: kafka-cluster
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 3
  replicas: 3